{
 "title": "AWS Backup",
 "description": "Visualize AWS Backup metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "backupvaultname",
    "label": "BackupVaultName",
    "query": {}
   },
   {
    "name": "resourcetype",
    "label": "ResourceType",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Jobs Completed Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BackupVaultName": "$backupvaultname", "ResourceType": "$resourcetype" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfBackupJobsCompleted",
     "namespace": "AWS/Backup",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "AWS/Backup", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "NumberOfBackupJobsCompleted", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(NumberOfBackupJobsCompleted) FROM \"AWS/Backup\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Backup Jobs Failed Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BackupVaultName": "$backupvaultname", "ResourceType": "$resourcetype" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfBackupJobsFailed",
     "namespace": "AWS/Backup",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "AWS/Backup", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "NumberOfBackupJobsCompleted", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(NumberOfBackupJobsCompleted) FROM \"AWS/Backup\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number Of Backup Jobs Completed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BackupVaultName": "$backupvaultname", "ResourceType": "$resourcetype" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfBackupJobsCompleted",
     "namespace": "AWS/Backup",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "AWS/Backup", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "NumberOfBackupJobsCompleted", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(NumberOfBackupJobsCompleted) FROM \"AWS/Backup\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number Of Backup Jobs Failed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BackupVaultName": "$backupvaultname", "ResourceType": "$resourcetype" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfBackupJobsFailed",
     "namespace": "AWS/Backup",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "AWS/Backup", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "NumberOfBackupJobsCompleted", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(NumberOfBackupJobsCompleted) FROM \"AWS/Backup\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number Of Backup Jobs Pending",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BackupVaultName": "$backupvaultname", "ResourceType": "$resourcetype" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfBackupJobsPending",
     "namespace": "AWS/Backup",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "AWS/Backup", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "NumberOfBackupJobsCompleted", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(NumberOfBackupJobsCompleted) FROM \"AWS/Backup\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Number Of Backup Jobs Running",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "BackupVaultName": "$backupvaultname", "ResourceType": "$resourcetype" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfBackupJobsRunning",
     "namespace": "AWS/Backup",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "sql": {
      "from": { "property": { "name": "AWS/Backup", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "NumberOfBackupJobsCompleted", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(NumberOfBackupJobsCompleted) FROM \"AWS/Backup\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<a style=\"float: right\" href=\"https://github.com/keivinonline/grafana-dashboards\" target=\"_blank\" title=\"Dashboard maintained by keivinonline\"><img src=\"https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png\" height=\"30px\" /></a>\n<div style=\"float: left\">\n<a style=\"xfloat: left\"  target=\"_blank\" href=\"https://docs.aws.amazon.com/aws-backup/latest/devguide/cloudwatch.html\">AWS Backup metrics with Amazon CloudWatch Documentation</a> | \n<a style=\"xfloat: left\"  target=\"_blank\" href=\"https://grafana.com/dashboards/707\">Installed from Grafana.com dashboards</a\n</div>\n<div style=\"clear:both; width:100%;height:0;font-size:0;\"></div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}